//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework EntityObject template.
// Code is generated on: 19/04/2018 15:13:19
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Metadata.Edm;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;

namespace CadastroEpi.Domain.Model
{

    /// <summary>
    /// There are no comments for CadastroEpi.Domain.Model.TipoIdentificador in the schema.
    /// </summary>
    [EdmEnumTypeAttribute(NamespaceName="CadastroEpi.Domain.Model", Name="TipoIdentificador")]
    [DataContract]
    public enum TipoIdentificador : int
    {
    
        /// <summary>
        /// There are no comments for TipoIdentificador.CNPJ in the schema.
        /// </summary>
        [EnumMember]
        CNPJ,    
        /// <summary>
        /// There are no comments for TipoIdentificador.CPF in the schema.
        /// </summary>
        [EnumMember]
        CPF
    }

}
