//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework EntityObject template.
// Code is generated on: 19/04/2018 15:13:19
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Metadata.Edm;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;

namespace CadastroEpi.Domain.Model
{

    /// <summary>
    /// There are no comments for CadastroEpi.Domain.Model.Empresa in the schema.
    /// </summary>
    /// <KeyProperties>
    /// EmpresaId
    /// </KeyProperties>
    [EdmEntityTypeAttribute(NamespaceName="CadastroEpi.Domain.Model", Name="Empresa")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Empresa : EntityObject    {
        #region Factory Method

        /// <summary>
        /// Create a new Empresa object.
        /// </summary>
        /// <param name="empresaId">Initial value of EmpresaId.</param>
        /// <param name="razaoSocial">Initial value of RazaoSocial.</param>
        /// <param name="tipoIdentificador">Initial value of TipoIdentificador.</param>
        /// <param name="identificador">Initial value of Identificador.</param>
        public static Empresa CreateEmpresa(int empresaId, string razaoSocial, TipoIdentificador tipoIdentificador, string identificador)
        {
            Empresa empresa = new Empresa();
            empresa.EmpresaId = empresaId;
            empresa.RazaoSocial = razaoSocial;
            empresa.TipoIdentificador = tipoIdentificador;
            empresa.Identificador = identificador;
            return empresa;
        }

        #endregion

        #region Properties
    
        /// <summary>
        /// There are no comments for EmpresaId in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public virtual int EmpresaId
        {
            get
            {
                int value = _EmpresaId;
                OnGetEmpresaId(ref value);
                return value;
            }
            set
            {
                if (_EmpresaId != value)
                {
                  OnEmpresaIdChanging(ref value);
                  ReportPropertyChanging("EmpresaId");
                  _EmpresaId = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("EmpresaId");
                  OnEmpresaIdChanged();
              }
            }
        }
        private int _EmpresaId;
        partial void OnGetEmpresaId(ref int value);
        partial void OnEmpresaIdChanging(ref int value);
        partial void OnEmpresaIdChanged();
    
        /// <summary>
        /// There are no comments for RazaoSocial in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(IsNullable=false)]
        [DataMemberAttribute()]
        public virtual string RazaoSocial
        {
            get
            {
                string value = _RazaoSocial;
                OnGetRazaoSocial(ref value);
                return value;
            }
            set
            {
                if (_RazaoSocial != value)
                {
                  OnRazaoSocialChanging(ref value);
                  ReportPropertyChanging("RazaoSocial");
                  _RazaoSocial = StructuralObject.SetValidValue(value, false);
                  ReportPropertyChanged("RazaoSocial");
                  OnRazaoSocialChanged();
              }
            }
        }
        private string _RazaoSocial;
        partial void OnGetRazaoSocial(ref string value);
        partial void OnRazaoSocialChanging(ref string value);
        partial void OnRazaoSocialChanged();
    
        /// <summary>
        /// There are no comments for TipoIdentificador in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(IsNullable=false)]
        [DataMemberAttribute()]
        public virtual TipoIdentificador TipoIdentificador
        {
            get
            {
                TipoIdentificador value = _TipoIdentificador;
                OnGetTipoIdentificador(ref value);
                return value;
            }
            set
            {
                if (_TipoIdentificador != value)
                {
                  OnTipoIdentificadorChanging(ref value);
                  ReportPropertyChanging("TipoIdentificador");
                  _TipoIdentificador = (TipoIdentificador)StructuralObject.SetValidValue((int)value);
                  ReportPropertyChanged("TipoIdentificador");
                  OnTipoIdentificadorChanged();
              }
            }
        }
        private TipoIdentificador _TipoIdentificador;
        partial void OnGetTipoIdentificador(ref TipoIdentificador value);
        partial void OnTipoIdentificadorChanging(ref TipoIdentificador value);
        partial void OnTipoIdentificadorChanged();
    
        /// <summary>
        /// There are no comments for Identificador in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(IsNullable=false)]
        [DataMemberAttribute()]
        public virtual string Identificador
        {
            get
            {
                string value = _Identificador;
                OnGetIdentificador(ref value);
                return value;
            }
            set
            {
                if (_Identificador != value)
                {
                  OnIdentificadorChanging(ref value);
                  ReportPropertyChanging("Identificador");
                  _Identificador = StructuralObject.SetValidValue(value, false);
                  ReportPropertyChanged("Identificador");
                  OnIdentificadorChanged();
              }
            }
        }
        private string _Identificador;
        partial void OnGetIdentificador(ref string value);
        partial void OnIdentificadorChanging(ref string value);
        partial void OnIdentificadorChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// There are no comments for Funcoes in the schema.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CadastroEpi.Domain.Model", "Empresa_Funcao", "Funcoes")]
        public virtual EntityCollection<Funcao> Funcoes
        {
            get
            {
                return ((IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Funcao>("CadastroEpi.Domain.Model.Empresa_Funcao", "Funcoes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Funcao>("CadastroEpi.Domain.Model.Empresa_Funcao", "Funcoes", value);
                }
            }
        }

        #endregion
    }

}
